name: CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            @brpaz/semantic-release-helm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
